version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/boombim-scheduling

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
