version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ec2-user
      timeout: 60

  ApplicationStart:
    - location: scripts/deploy.sh
      runas: ec2-user
      timeout: 300
