spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

open-api:
  api-key: ${OPEN_API_KEY}

s3:
  bucket-name: ${S3_BUCKET}
  region: ${S3_REGION}
  base-url: ${S3_BASE_URL}
  placeholder-key: ${S3_PLACEHOLDER_KEY}

kakao:
  base-url: https://dapi.kakao.com
  scheme: "KakaoAK "
  api-key: ${KAKAO_COORDINATE_TO_REGION_CODE_API_KEY}

official-congestion:
  purge:
    enabled: true
    days: 3
    batch-size: 10000
