spring:
  application:
    name: boombim-openapi-dev

  aot:
    enabled: false

  config:
    import:
      - optional:file:env/dev.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
